version: '3.8'

services:
  backend:
    build:
      context: ./backend/softtek
    volumes:
      - ./backend/softtek/db_softtek:/app/db_softtek
      - ./data:/data
    entrypoint: ["python", "main.py"]

  frontend:
    build:
      context: .
    ports:
      - "80:80"
