services:
  backend:
    build:
      context: ./backend/softtek
    volumes:
      - ./backend/softtek/db_softtek:/app/db_softtek
      - ./frontend/data:/frontend/data
    entrypoint: ["sh", "-c", "python main.py && echo 'http://localhost:80 ✅'"]

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    volumes:
      - ./frontend/data:/usr/share/nginx/html/frontend/data